language: node_js
node_js:
  - '9'
script:
  - yarn test
  - yarn build
  - node dist/main.cjs.js
deploy:
  local-dir: templates
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
